### ISSUE TITLE
How do you use this with webpack 2?

### ISSUE THREAD

**Issue by ciocan** [shepherdwind/css-hot-loader#1]

**Comment by shepherdwind** [comment]
Sorry, This loader just worked on webpack 1.x . I don't use webpack 2 yet.

I will try to resolve the problem soon.

**Comment by faceyspacey** [comment]
where do you put the loader here for example:

```
{
        test: /\.css$/,
        use: ExtractTextPlugin.extract({
          fallback: "style-loader",
          use: "css-loader?modules&localIdentName=[name]__[local]--[hash:base64:5]"
        })
      },
```

**Comment by shepherdwind** [comment]
@faceyspacey webpack 2.x can use those config

```js
module: {
  rules: [
    {
      test: /\.css$/,
      use: ['css-hot-loader'].concat(ExtractTextPlugin.extract({
        fallback: 'style-loader',
        use: 'css-loader'
      })),
    },
  ]
}
```

Please use version 1.0.2 .

**Comment by faceyspacey** [comment]
awesome! trying it now.

**Comment by shepherdwind** [comment]
@ciocan  I am sorry, I just forget to fix this issue .

**Comment by faceyspacey** [comment]
It's not working for me. No stylesheet is appearing in the `head`. 

Here's what I have:
```
{
        test: /\.css$/,
        use: ['css-hot-loader'].concat(ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: 'css-loader?modules&localIdentName=[name]__[local]--[hash:base64:5]'
        }))
      },
  ]
},
plugins: [
    new ExtractTextPlugin({
      filename: '[name].css',
    }),
...
```

**Comment by faceyspacey** [comment]
In fact, it seems to break HMR for even javascript. HMR does not work at all after installing this. And I've tested to make sure regular HMR for js and css works--here's my regular css loader commented out:

```
// {
//   test: /\.css$/,
//   exclude: /node_modules/,
//   loaders: [
//     'style-loader',
//     'css-loader?modules&localIdentName=[name]__[local]--[hash:base64:5]',
//   ],
// },
```

**Comment by shepherdwind** [comment]
@faceyspacey Can You send me a tiny demo? So I can try this on my compute .

If it is convenient for you, send code to my email(eward.song at gmail.com) or just give me a url which I can find the demo code.

**Comment by shepherdwind** [comment]
Here https://github.com/shepherdwind/react-hot-boilerplate/tree/next is my demo code, which css and js are all work fine .

**Comment by faceyspacey** [comment]
ok, I'm going to try it tomorrow as it's the end of my day, but something tells me it has to do with `allChunks: false` in mine since your example has `allChunks: true`. ...i'm working on a PR to output a css file per chunk rather than a single one--i wonder how your plugin will behave then.
