### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by daryn-k** [shepherdwind/css-hot-loader#10]
It doesn't work for me. No any effects.

webpack 2 config:

```
module: {
    rules: [
      {
        test: /\.css$/,
        use: ['css-hot-loader'].concat(ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: 'css-loader'
        })),
      },
    ],
    loaders: [
      {
        test: /\.css$/,
        loader: ExtractTextPlugin.extract('style-loader', 'css-loader')
      },
      ....
```
css required by js, same names for css and js

**Comment by shepherdwind** [comment]
I have an mini demo [example](https://github.com/shepherdwind/css-hot-loader/tree/master/examples/simple). Can you modify it and reproduce your problem again? So I can find out where is wrong.

**Comment by daryn-k** [comment]
Thanks. Now it works!
