### ISSUE TITLE
Fix typo in description?

### ISSUE THREAD

**Issue by berfarah** [shepherdwind/css-hot-loader#14]
Hi! Thanks for making this, it's immensely helpful! 😃 

I don't mean to be nitpicky but I figure this may make a better first impression to new visitors of the repo:
![image](https://user-images.githubusercontent.com/1395723/27963471-09d6bc3c-62ea-11e7-9082-760cf8702242.png)
(should be 'support')

**Comment by shepherdwind** [comment]
Fix now.

**Comment by berfarah** [comment]
Thanks!
