### ISSUE TITLE
Breaks when using sourceMap

### ISSUE THREAD

**Issue by mgcrea** [shepherdwind/css-hot-loader#15]
When using:

```
    options: {
      sourceMap: true
    }
```

In both cssLoader, postcssLoader & sassLoader, I'm encountering full page reloads instead of hot reloads.

I also get strange errors in the console:

```
404 GET blob:http://localhost:3000/dcb2d879-2491-4305-9eaf-a30154ab4fdb?1502374626966 
```

PS: I'm not using ExtractTextLoader but rely on your package to get live reload with css modules.

**Comment by shepherdwind** [comment]
A little demo code will be more helpful. Can you modify the [simple example](https://github.com/shepherdwind/css-hot-loader/tree/master/examples/) , and send a pr . So I can reproduce your problem.

**Comment by mgcrea** [comment]
I've just added a PR with a reproducible test-case. Hope it helps.

**Comment by shepherdwind** [comment]
I tried you example code. But I find that you project do not need css-hot-loader, and the hot loader work fine.

I change the file `config-overrides.js`

```diff
   // We need `css-hot-loader` for hot reload to work with css modules
-  stylesModuleLoader.use.unshift(require.resolve('css-hot-loader'));
+  // stylesModuleLoader.use.unshift(require.resolve('css-hot-loader'));
```

Then run `npm start` , change App.css, the page reload with style change.

**Comment by mgcrea** [comment]
@shepherdwind, hum indeed not sure how I ended up with that conclusion but it does look like to be working fine without it, will re-open if I can reproduce. Thanks ;-).
