### ISSUE TITLE
Not working with Webpack 3.x

### ISSUE THREAD

**Issue by debanjanbasu** [shepherdwind/css-hot-loader#18]

**Comment by shepherdwind** [comment]
😅 So many versions.

**Comment by debanjanbasu** [comment]
3.5.5 To be precise. I think it's the latest one. Sorry, my bad for not mentioning the version.

**Comment by shepherdwind** [comment]
@debanjanbasu I update my demo to 3.x version, which work fine.

https://github.com/shepherdwind/css-hot-loader/tree/webpack3

I don't know what you said `Not working` very well. Maybe you can provide a reproduction example to me, will be more helpful.
