### ISSUE TITLE
Call some function after CSS has reloaded

### ISSUE THREAD

**Issue by ghost** [shepherdwind/css-hot-loader#23]
In my particular stack, I have a JS file which contains a map of each CSS class name to its hashed version.  For hot reloading to work properly, this JS file needs to be regenerated after the CSS has changed.  I already have a function to regenerate and reload the file, I just need a good way to call this function after the CSS has changed.

Would it make sense to add something to this library that will allow this?

**Comment by shepherdwind** [comment]
PR welcome 😀

**Comment by shepherdwind** [comment]
Maybe we can add a config , and put this js reload function on Window . Then call you config function by window.foo .

**Comment by ghost** [comment]
Okay cool.  I'll submit a PR when I get a chance (probably Monday).

**Comment by ghost** [comment]
Looks like the problem I'm having is mostly unrelated to this library.  Webpack 3 is erroneously saying a CSS file hasn't changed when it has.
