### ISSUE TITLE
Circumvent project assumptions

### ISSUE THREAD

**Issue by satazor** [shepherdwind/css-hot-loader#3]
At the moment, if you have a main.js file it's expected that the css lives in main.css.

Though, people like me like to tweak the output folders of js & css files, e.g.: js/main.js and css/main.css
As you see, this violates the assumption that the css file lives in the same folder as the js file. Is it possible to have an option to make it more flexible?

Thanks.

**Comment by StevenDoesStuffs** [comment]
Yeah, this is an issue as most people arent going to have js and css in the same folder.

**Comment by StevenDoesStuffs** [comment]
Also, that won't work with caching where your main file doesn't have the same name due to hashing.

**Comment by shepherdwind** [comment]
I add an option `fileMap`, so you can use is to define you reload rule.

See the doc https://github.com/shepherdwind/css-hot-loader#filemap for more information.

**Comment by stereokai** [comment]
@shepherdwind can you please explain this problem?
