### ISSUE TITLE
HELP ME

### ISSUE THREAD

**Issue by long-hp** [shepherdwind/css-hot-loader#31]
css-hot-loader worked
but what is it?
https://drive.google.com/file/d/1JgTkd4yV05zGVrqCFjP6G_kpsIIP8ZFM/view?usp=drivesdk

**Comment by shepherdwind** [comment]
It this error throw case by css-hot-loader? I am not sure.

Can you try modify my example code of the repo, So that I can reproduce you problem on my compute. If I can't reproduce it, I can not find the problem just by the picture you provide.

**Comment by long-hp** [comment]
tks <3 it worked
