### ISSUE TITLE
Help pls - HMR  Cannot apply update. Need to do a full reload!

### ISSUE THREAD

**Issue by tienhienit** [shepherdwind/css-hot-loader#32]
[HMR] Cannot apply update. Need to do a full reload!
[HMR] Error: Aborted because 84 is not accepted

IMG:
https://drive.google.com/file/d/1EG47Kz46-73I4owAeYXazUjlZAmgmMtI/view?usp=drivesdk

**Comment by shepherdwind** [comment]
Give me a demo example code, so I can reproduce this problem.

You can fork this repo and modify examples code https://github.com/shepherdwind/css-hot-loader/tree/master/examples , Then send a pull request.
