### ISSUE TITLE
Uncaught TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by trevorlasn** [shepherdwind/css-hot-loader#4]
When starting the project with `css-hot-loader` included - the project returns `Uncaught TypeError: Cannot read property 'call' of undefined` -- after saving a component/file it disappears and starts working again.

Please do a git clone of this repository, make sure you're on branch `chapter-5`

https://github.com/wesharehoodies/webpack-2.0-from-scratch/tree/chapter-5

After cloning, `npm i && npm run start` -- the webpack compiles perfectly but the browser produces couple errors which are solvable by saving a file. Any hotfixes planned?

Indrek

**Comment by shepherdwind** [comment]
I am sorry, I did not watch my project. So I miss you issue from notifications.

I fixed this problem now, 1.0.4 publiched. You can try you project again now, which should work fine.
