### ISSUE TITLE
can't work very well

### ISSUE THREAD

**Issue by luckykun** [shepherdwind/css-hot-loader#41]
Hi, First of all, thank you for this tool, which is very good to me.

But I've got a problem recently.  When I use the `postcss-loader`  to handle the CSS file。And Using `postcss-global-import` to refer to the global CSS file。

css-hot-loader can't work very well。

I hope you can solve this problem. Thank you very much！！！

````js
// index.js
import './index.pcss';

// index.pcss（this is the point）
@global-import './globla.pcss';

````

When I modify the content of `globla.pcss`,   `css-hot-loader` can't work very well。

**Comment by shepherdwind** [comment]
Can you provide me an little example, so I can reproduce the problem you meet with.

**Comment by shepherdwind** [comment]
If you don't provide more information for this issue, I will close it now.

You can reopen this anytime. Thanks for you feedback.
