### ISSUE TITLE
Code spliting

### ISSUE THREAD

**Issue by onrige** [shepherdwind/css-hot-loader#42]
Hey. First thanks for such great tool man, it's really helpful :) But I have a question.

What about code spliting? After including react-loadable (witch also support hot reload by HOC) I see that this package works not like before. In console I see updated styles.css file and then `[HMR] Reload all css` at the end that reload all css and I see it like flicker.

So..may be you have any ideas why does it happens and how can we resolve it?

**Comment by shepherdwind** [comment]
Because This plugin reload css trigger from js file. To find which css should reload, I use `document.currentScript` to find the js file which required css file.

You can get more information by this https://github.com/shepherdwind/css-hot-loader#how .

If use code split, This plugin maybe can not find the right file path, So then all css will reload every time.

**Comment by shepherdwind** [comment]
1.4.0 support reloadAll config, so you can reload every css file now. see https://github.com/shepherdwind/css-hot-loader/issues/44

**Comment by onrige** [comment]
It doesn't work with MiniCssExtractPlugin in my case

```
{
    test: /\.less$/,
    use: [
      { loader: 'css-hot-loader', options: { reloadAll: true } },
      'style-loader',
      MiniCssExtractPlugin.loader,
      'css-loader',
      'postcss-loader',
      'less-loader',
    ],
},
```

**Comment by shepherdwind** [comment]
What version do you used?  This feature worked on 1.4.0 version.

**Comment by onrige** [comment]
The last one (1.4.0)

**Comment by shepherdwind** [comment]
How about try my example code https://github.com/shepherdwind/css-hot-loader/blob/0a1be904c9e2d9ac23079f739606e99933539f64/examples/code-split/webpack.config.js#L19-L23 . If this code-split example https://github.com/shepherdwind/css-hot-loader/tree/master/examples/code-split work fine for you ?

Or maybe you can give me you tiny example code . I will try it and find the problem.

**Comment by onrige** [comment]
I also tried with `fileMap` option but it doesn't work for me.

I forked and modified your [code-split example](https://github.com/onrige/css-hot-loader/tree/master/examples/code-split) (update to webpack v4, use MiniCssExtractPlugin instead of ExtractTextWebpackPlugin) and all works even without `reloadAll` option and I dont know how to explain this :) May be I something missed?

**Comment by shepherdwind** [comment]
There is a issue about webpack 4 compatibility #37 . `reloadAll` option will reload all css on page. Default reload the css which name is the same as the entry js file name.

For example, If entry file name is `foo.js`, and foo.js import `foo.css`. When `foo.css` modified, The file change event will dispatch on file `foo.js`, and this plugin will reload `foo.css` .

But for code split, maybe when you modify `foo.css`, this css maybe extract to common.css, So we can use reloadAll to force reload every css file.
