### ISSUE TITLE
Weird bug with code splitting on initial page load

### ISSUE THREAD

**Issue by Bram-Zijp** [shepherdwind/css-hot-loader#43]
When I load page 1 with chunks: `main.js main.css` `1.js 1.css` and I change something part of chunk `1.css`, the `main.css` gets reloaded.
When I load page 1 then navigate (with react-router-dom) to page 2 wich adds `2.js 2.css` to the head, and I change something in `2.css`, `2.css` is hot reloading fine.

I'm using react-loadable to split chunks automatically but this probably unrelated.

```
"css-hot-loader": "^1.3.9",
 "mini-css-extract-plugin": "^0.4.0",
"webpack": "^4.6.0",
"react-loadable": "^5.3.1",
```

**Comment by ScriptedAlchemy** [comment]
https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/issues/80

**Comment by shepherdwind** [comment]
https://github.com/shepherdwind/css-hot-loader/issues/44
