### ISSUE TITLE
[hot reload not work] With splitChunks, reload the mismatch css file

### ISSUE THREAD

**Issue by genshinw** [shepherdwind/css-hot-loader#44]
With  my follow webpack config, I get common.chunk.css , page1.chunk.css , page2.chunk.css, common.chunk.js, page1.chunk.js, page2.chunk.js 

In this conditon: 
If I import 'b.scss' both in page1 and page2 chunk , The 'b.css' content with be extract in common.chunk.css;
Then 'HotModuleReplaceMent.js' with hot reload 'page1.chunk.css' according to 'page1.chunk.js' when I try to change 'b.scss' import by page1Chunk. That is wrong ,I want to reload 'common.chunk.css';

If any other way to fix this problem? 

```js

entry: {
page1: '...',
page2: '...'
}
optimization: {
  splitChunks: {
            chunks: 'all',
            cacheGroups: {
                default: false,
                 common: {
                    chunks: 'initial',
                    name: 'common',
                    minChunks: 2,
                    minSize: 30000
              }
        }
   }
}
module: { 
  rules: [
{
        test: /\.scss$/,
        use: [
            'css-hot-loader',
            MiniCssExtractPlugin.loader,
            {loader: 'css-loader', options: {sourceMap: true}},
            {loader: 'sass-loader', options: {sourceMap: true}}
    ]}
   ]
}

plugins: [
new MiniCssExtractPlugin({
 
          filename: "[name].css",
            chunkFilename:"[name].chunk.css"
        }))
]
 ```

**Comment by shepherdwind** [comment]
There are some examples here https://github.com/shepherdwind/css-hot-loader/tree/master/examples . Can you modify one of those example, and reproduce the problem , then give me the you code url. 

So that I can reproduce the problem on my compute. Which will be very helpful for me, to resolve your problem.

**Comment by genshinw** [comment]
@shepherdwind I modify commons-chunk example, the code url: 
[commons-chunk-modify.zip](https://github.com/shepherdwind/css-hot-loader/files/2089255/commons-chunk-modify.zip)


When I modify 'common.css' , it reLoad inde1.css.
![image](https://user-images.githubusercontent.com/12270447/41221115-d5f36a66-6d95-11e8-9ed1-a4e15a1b6246.png)

**Comment by genshinw** [comment]
@shepherdwind 
https://github.com/lshih/webpack-extract-css-hot-reload/blob/master/hotModuleReplacement.js
I think it`s another way to find the real hot reload file.

**Comment by shepherdwind** [comment]
@ElvisWang27 you said that

> I think it`s another way to find the real hot reload file.

Maybe you can send a pr to this repo, that will be very helpful.

**Comment by genshinw** [comment]
@shepherdwind 
https://github.com/lshih/webpack-extract-css-hot-reload/blob/master/hotModuleReplacement.js
This is not my idea. It use 'document.querySelectorAll('link[tag]')' with tag to mark the hot reload file.

**Comment by ScriptedAlchemy** [comment]
https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/issues/80

**Comment by shepherdwind** [comment]
1.4.0 support `reloadAll` option now.

https://github.com/shepherdwind/css-hot-loader/blob/0a1be904c9e2d9ac23079f739606e99933539f64/examples/code-split/webpack.config.js#L19-L23
