### ISSUE TITLE
Want help maintaining this?

### ISSUE THREAD

**Issue by ScriptedAlchemy** [shepherdwind/css-hot-loader#45]
Hey dude, dunno if you plan to keep working actively on your HMR stuff.  Im the maintainer of extract-css-chunks which its own HMR was based off your work. 

If you plan on keeping it active, we could collaborate on this repo. Otherwise if you are losing interested in it - Im willing to take over your work and advance it

**Comment by shepherdwind** [comment]
I am only want the css hot reload feature work. So, I am glad that you want to maintainer this repo.

So, How should I do to transfer this repo to you?

**Comment by ScriptedAlchemy** [comment]
I’ll look it up tomorrow and send you the details. Good work so far! Thanks for your response

**Comment by ScriptedAlchemy** [comment]
Okay, if you go to https://github.com/shepherdwind/css-hot-loader/settings

You will see at the bottom: *Transfer ownership*

**Comment by shepherdwind** [comment]
I do not think that is a good idea. This repo do not need too much time to maintain it.

**Comment by shepherdwind** [comment]
I will continue to maintain this tool myself.

**Comment by ScriptedAlchemy** [comment]
Okay no worries, Ill likely open up some PR's to your repo in the near future. 

Was just asking IF you did not plan on maintaining it :)
