### ISSUE TITLE
Adding the content hash in the css filename breaks reloading

### ISSUE THREAD

**Issue by aytee17** [shepherdwind/css-hot-loader#52]
Including the content hash in the filename causes reloading to fail without errors.
```
new MiniCssExtractPlugin({
    filename: "[name].style.[contenthash].css"
}),
```
This doesn't necessarily need to be fixed since the content hash isn't required in development, but I used the above code in my base webpack configuration because there wasn't any reason (before this issue) to have different names for development and production. Others might stumble upon the same problem, so maybe this could be mentioned in the docs?

**Comment by shepherdwind** [comment]
Maybe you should try the option `reloadAll`, which will reload all css . https://github.com/shepherdwind/css-hot-loader#reloadall 

This config will break the css path resolve rule(a.js entry file will reload a.css), which will cause reload fail.

**Comment by ScriptedAlchemy** [comment]
You shouldn’t be hashing development files anyways. Contenthash is production

**Comment by rluncasu** [comment]
> You shouldn’t be hashing development files anyways. Contenthash is production

Why ? I thought contenthash ensures your browser is not caching between builds which looks to me like a really useful feature in development. Of course, one could argue that you could discard the minicssextractplugin alltoghether in development but then that would defeat the purpose of this plugin, wouldn't it ?

**Comment by ScriptedAlchemy** [comment]
Open your devtools, go to network, check the “disable cache” box. Problem solved.

**Comment by ScriptedAlchemy** [comment]
Hot reloading doesn’t play nice with hashing files in development. It’s a known issue that has more to do with webpack than this loader
