### ISSUE TITLE
Object doesn't support property or method 'remove'

### ISSUE THREAD

**Issue by Nettsentrisk** [shepherdwind/css-hot-loader#55]
The remove method in this context throws an error in IE (11):

```javascript
newEl.addEventListener('load', function () {
    newEl.isLoaded = true;
    el.remove();
  });
  newEl.addEventListener('error', function () {
    newEl.isLoaded = true;
    el.remove();
  });
```
Since the DOM web API is outside the scope of babel polyfills, perhaps this project should include a polyfill of some sort for this? Or rewrite the code to be more generally compatible (i.e. `this.parentNode.removeChild(this)`).

**Comment by shepherdwind** [comment]
New version 1.4.4  published.

**Comment by Nettsentrisk** [comment]
Thanks, that was quick!
