### ISSUE TITLE
Union with `mini-css-extract-plugin`

### ISSUE THREAD

**Issue by alexander-akait** [shepherdwind/css-hot-loader#58]
Hi, great work, we have PR what add hmr feature https://github.com/webpack-contrib/mini-css-extract-plugin/pull/334, you may want to participate and help to implement this feature. We glad any help.

**Comment by ScriptedAlchemy** [comment]
The hot Loader is actually based off some of your work. We spoke a while ago regarding extract-css-chunks, which is now merging with mini-css

Would be great to work together! I think I’ve solved the reload all and some css modules stuff as well.  Last I checked the hot loader sometimes needed a option for these.

**Comment by shepherdwind** [comment]
I am love to see that the two plugin can be merged together. After that mr merged, I will add some tip to remind css-hot-loader user to migrate, and archive this repo.

**Comment by ScriptedAlchemy** [comment]
Fantastic! @shepherdwind your original work on hot loading is greatly appreciated. I hope you consider maintaining mini-css with us if or when you have time :)
