### ISSUE TITLE
Not working if the CSS is an entry point

### ISSUE THREAD

**Issue by Danita** [shepherdwind/css-hot-loader#7]
I'm using Webpack2. In my configuration, SCSS files aren't required by javacript, but they are entry points by themselves, like this:

```javascript
var config = {
  entry: {
    bootstrap: path.join(DIRS.ASSETS, './css/bootstrap.scss'),
    main: path.join(DIRS.ASSETS, './css/main.scss'),
    // etc
  },
  module: {
    rules: [
      {
        test: /\.scss$/,
        use: ['css-hot-loader'].concat(ExtractTextPlugin.extract({
          use: [
            { loader: "css-loader" },
            { loader: "sass-loader" }
          ],
        }))
      },
   ]
}
```

When I modify the source SCSS files, they are not hot reloaded. It triggers the hot update, but nothing is updated. Any ideas?

**Comment by shepherdwind** [comment]
I don't know If hmr support you case. Let me have a look.

**Comment by shepherdwind** [comment]
I write an demo [example](https://github.com/shepherdwind/webpack-2.0-from-scratch/tree/chapter-5).

If css is an entry point, webpack will wrap this css file with a js which only require the entry file. For example, entry file `bootstrap: 'bootstrap.sass'`, will output two file `bootstrap.js, bootstrap.css`.

CSS hot reload need the js to trigger and listen file change, so, You need load the `bootstrap.js` in dev env.

I am sorry to reply so latter, It's a little busy recently.
