### ISSUE TITLE
when App updated. Recompiling...,the web page will have no any style

### ISSUE THREAD

**Issue by lumia2046** [shepherdwind/css-hot-loader#8]
when I have revised css file
then App updated. Recompiling...,
the web page will have no any style unless css reload all css

**Comment by lumia2046** [comment]
style will be ok when hot -loading
![image 1](https://user-images.githubusercontent.com/20272241/27175730-b5622dec-51f2-11e7-9550-880a29ecdb87.jpg)
style will be none when hot -loading
![image 2](https://user-images.githubusercontent.com/20272241/27175789-e25e0dfc-51f2-11e7-9843-dbc1af624032.png)

**Comment by lumia2046** [comment]
css reload all css twice ,style will be none when hot -loading

**Comment by shepherdwind** [comment]
Can you provide a demo ? For example, modify this repo https://github.com/wesharehoodies/webpack-2.0-from-scratch/tree/chapter-5 , and then give me a github url, so I can reproduce you problem.

**Comment by lumia2046** [comment]
https://github.com/lumia2046/css-loader-issue.git
clone this repo
then
npm install 
npm start
enter http://localhost:3456
enter folder : css-loader-issue\src\components\common\Header\styles.css
.container{
	height: 90px;
	background: RGB(3,169,245);
}
change height: 90px to height: 190px ,after hot load,then change to height: 90px 
you will see style disappear sometimes when hot loading
if the problem not occur ,please:
change the height to 290 then to 30
or crtl + c cmd then restart it
or clean the browser history
the problem did not occur everytime ,hope you will try more

**Comment by lumia2046** [comment]
when you add a new className for jsx html element , you need to refresh the page then you can see the style changed

**Comment by shepherdwind** [comment]
css 消失的问题是修改 class 名字的时候出现的，因为你用了 css module 插件，所有的 className 会基于 className 的 md5 来 hash 一下，所以修改 className 的时候，老的 css 全部失效了，但这时候如果没有重新 load 一遍 css ，会出现没有样式的情况。

这个不是问题的。

**Comment by shepherdwind** [comment]
你这种配置场景有两个方式可以搞定

- 修改的时候先改 css 的 className ，然后再改 jsx
- 开发环境去掉 css module

修改 css 里面 className 的时候，如果先改 js ，js 是拿不到对应的 css 里面对应的变量（因为这时候 css 还没改，这个 className 不存在）。所以要先修改 css ，然后再改 js 。

第二种方案去掉 css module 也行，这样就不会有 js 里面 className 和 css 里面 className 不一致的情况，不会有依赖场景存在。

**Comment by shepherdwind** [comment]
另外，建议看看 markdown 语法规则， https://guides.github.com/features/mastering-markdown/ ，不要直接把代码贴上来，那样不好看。
